// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAhWkEus8J7X61TgHsM9W-LvCQpeL2Qzqc',
    appId: '1:233539778173:web:5442c7d6d48035839aa314',
    messagingSenderId: '233539778173',
    projectId: 'mes-commandements-cddb2',
    authDomain: 'mes-commandements-cddb2.firebaseapp.com',
    storageBucket: 'mes-commandements-cddb2.firebasestorage.app',
    measurementId: 'G-ZBL91675TK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChxp9yxCAihAJkck0QEyXdcnqx6eLytbQ',
    appId: '1:233539778173:android:aaa9140d037f57629aa314',
    messagingSenderId: '233539778173',
    projectId: 'mes-commandements-cddb2',
    storageBucket: 'mes-commandements-cddb2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSOj9GQqigJGfZyQMTVFR2trkdmZi4BpM',
    appId: '1:233539778173:ios:8ea4129304a5707a9aa314',
    messagingSenderId: '233539778173',
    projectId: 'mes-commandements-cddb2',
    storageBucket: 'mes-commandements-cddb2.firebasestorage.app',
    iosBundleId: 'com.example.mesCommandements',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSOj9GQqigJGfZyQMTVFR2trkdmZi4BpM',
    appId: '1:233539778173:ios:8ea4129304a5707a9aa314',
    messagingSenderId: '233539778173',
    projectId: 'mes-commandements-cddb2',
    storageBucket: 'mes-commandements-cddb2.firebasestorage.app',
    iosBundleId: 'com.example.mesCommandements',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAhWkEus8J7X61TgHsM9W-LvCQpeL2Qzqc',
    appId: '1:233539778173:web:1b50bcccc512d8589aa314',
    messagingSenderId: '233539778173',
    projectId: 'mes-commandements-cddb2',
    authDomain: 'mes-commandements-cddb2.firebaseapp.com',
    storageBucket: 'mes-commandements-cddb2.firebasestorage.app',
    measurementId: 'G-5M0SQMLZZ0',
  );
}
